# Generated by Django 3.1.2 on 2020-11-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hogwarts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='wizard',
            field=models.CharField(choices=[('1', 'Harry Potter'), ('2', 'Ron Weasley'), ('3', 'Heromione Granger'), ('4', 'Neville Longbottom'), ('5', 'Luna Lovegood'), ('6', 'Ginny Weasley')], default=0, max_length=1),
        ),
    ]
