# Generated by Django 3.1.2 on 2020-11-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hogwarts', '0002_players_wizard'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='player_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
